#!/bin/bash
# Quick Start Guide for Command Line Hero

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║          🦸‍♂️  COMMAND LINE HERO - QUICK START  🦸‍♂️              ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "📦 TO RUN:"
echo "   python3 cli.py"
echo "   or"
echo "   ./cli.py"
echo ""
echo "🎯 ESSENTIAL COMMANDS:"
echo "   help          - Show all commands"
echo "   ls -l         - List files (detailed)"
echo "   cd <dir>      - Change directory"
echo "   pwd           - Show current directory"
echo "   cat <file>    - Display file"
echo "   clear         - Clear screen"
echo "   exit          - Quit CLI"
echo ""
echo "✨ ADVANCED FEATURES:"
echo "   Tab           - Auto-complete commands/files"
echo "   Ctrl+R        - Reverse search history"
echo "   ll            - Alias for 'ls -l'"
echo "   ..            - Alias for 'cd ..'"
echo ""
echo "📝 FILE OPERATIONS:"
echo "   touch <file>  - Create file"
echo "   mkdir <dir>   - Create directory"
echo "   cp <s> <d>    - Copy"
echo "   mv <s> <d>    - Move/rename"
echo "   rm <file>     - Remove file"
echo "   rmdir <dir>   - Remove directory"
echo ""
echo "🔍 TEXT TOOLS:"
echo "   grep <p> <f>  - Search in file"
echo "   head <f> [n]  - First n lines"
echo "   tail <f> [n]  - Last n lines"
echo "   wc <file>     - Count lines/words"
echo "   diff <f1> <f2> - Compare files"
echo "   sort <file>   - Sort lines"
echo ""
echo "🌲 OTHER USEFUL:"
echo "   find <name>   - Find files"
echo "   tree          - Show directory tree"
echo "   du <path>     - Disk usage"
echo "   env           - Environment vars"
echo "   which <cmd>   - Locate command"
echo "   alias x='y'   - Create shortcut"
echo ""
echo "✅ ALL TESTS PASSED: 7/7"
echo ""
echo "Ready to start? Run: python3 cli.py"
echo ""
